apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-root
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/Andach797/case-study
    targetRevision: main
    path: argocd/apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
