apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
data:
  LOG_LEVEL: "{{ .Values.app.logLevel }}"
  MAX_UPLOAD_MB: "{{ .Values.app.maxUploadMB }}"
