apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-nginx.fullname" . }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "web.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "web.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ .Values.configMapName }}
          env:
            - name: CONFIG_SECRET_ARN
              value: "{{ .Values.secretArn }}"
          volumeMounts:
            - name: shared-static
              mountPath: /app/uploads
        - name: nginx
          image: "{{ .Values.nginxImage.repository }}:{{ .Values.nginxImage.tag }}"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: shared-static
              mountPath: /usr/share/nginx/html
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: shared-static
          persistentVolumeClaim:
            claimName: shared-static-pvc
        - name: nginx-conf
          configMap:
            name: nginx-conf
