apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    {{- include "web-nginx.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
      listen 80;
      location / { proxy_pass http://127.0.0.1:8000; }
      location /uploads/ {
        alias /usr/share/nginx/html/;
        autoindex on;
      }
    }
