{{- /*
 SecretProviderClass
*/}}
{{- $spcName := .Values.secretProviderClassName | default (printf "%s-spc" (include "web-nginx.fullname" .)) -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $spcName }}
  namespace: {{ .Release.Namespace | default "default" }}
  labels:
    {{- include "web-nginx.labels" . | nindent 4 }}
spec:
  provider: aws
  parameters:
    objects: |
      # the *source* secret in Secrets Manager
      - objectName: "{{ .Values.secretArn }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "CSV_BUCKET"
            objectAlias: "CSV_BUCKET"
  secretObjects:
    - secretName: web-app-runtime
      type: Opaque
      data:
        - objectName: CSV_BUCKET
          key: CSV_BUCKET
