apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: web-app-sm
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.secretArn }}
        objectType: "secretsmanager"
  secretObjects:
    - secretName: web-app-runtime
      type: Opaque
      data:
        - objectName: CSV_BUCKET
          key: CSV_BUCKET
