# deployment
replicaCount: 2

image:
  repository: ""
  tag: latest
  pullPolicy: IfNotPresent

nginxImage:
  repository: nginx
  tag: 1.27-alpine

# config & secrets
configMapName: web-app-config
secretArn: ""

app:
  logLevel: "INFO"
  maxUploadMB: "5"

# efs parameters
efs:
  fileSystemId: ""
  accessPointId: ""
  directoryPerms: "750"
  uid: "1000"
  gid: "1000"

storageClassName: efs-sc
# service
service:
  type: LoadBalancer
  port: 80

# autoscaling
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPU: 60

serviceAccount:
  create: false
  name: case-dev-web-app-sa

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

secretProviderClassName: ""
mountSecretsPath: /app/secrets
