apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nginx
  labels:
    app: web-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      labels:
        app: web-nginx
    spec:
      serviceAccountName: case-dev-web-app-sa
      containers:
      - name: web
        image: 562538630478.dkr.ecr.eu-central-1.amazonaws.com/web-app-dev:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: web-app-config
        env:
        - name: CONFIG_SECRET_ARN
          value: arn:aws:secretsmanager:eu-central-1:562538630478:secret:case-dev-web-app-HLdYDA
        volumeMounts:
        - name: shared-static
          mountPath: /app/uploads
      - name: nginx
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: shared-static
          mountPath: /usr/share/nginx/html
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: shared-static
        persistentVolumeClaim:
          claimName: shared-static-pvc
      - name: nginx-conf
        configMap:
          name: nginx-conf
